version: "3"

networks:
    default:
        external:
            name: docker-net

services:
    influxdb:
        image: influxdb:2.0.4-alpine
        container_name: "influxdb"
        volumes:
            - /data2/docker_data/influxdb:/var/lib/influxdb2
            - /data2/docker_data/influxdb_config:/etc/influxdb2
        ports:
            - 8086:8086
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=dosue
            - DOCKER_INFLUXDB_INIT_PASSWORD=dosue-rr
            - DOCKER_INFLUXDB_INIT_ORG=hogeorg
            - DOCKER_INFLUXDB_INIT_BUCKET=hogebucket
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000 
        user: 'root'
        volumes:
            - /data2/docker_data/grafana:/var/lib/grafana
        depends_on:
            - influxdb
        environment:
            - GF_SERVER_ROOT_URL=http://localhost:3000
            - GF_SECURITY_ADMIN_PASSWORD=dosue
